# Generated by Django 6.0.6 on 2026-07-05 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('snack', 'Полдник'), ('dinner', 'Ужин')], max_length=30)),
                ('calories', models.PositiveIntegerField()),
                ('protein_g', models.FloatField(default=0)),
                ('fat_g', models.FloatField(default=0)),
                ('carbs_g', models.FloatField(default=0)),
                ('cooking_time_minutes', models.PositiveIntegerField(default=15)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('muscle_group', models.CharField(max_length=100)),
                ('difficulty', models.CharField(choices=[('easy', 'Легко'), ('medium', 'Средне'), ('hard', 'Сложно')], default='easy', max_length=20)),
                ('equipment', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('protein', 'Белок'), ('carb', 'Углеводы'), ('fat', 'Жиры'), ('vegetable', 'Овощи'), ('fruit', 'Фрукты'), ('dairy', 'Молочные продукты'), ('drink', 'Напитки'), ('other', 'Другое')], max_length=30)),
                ('calories_per_100g', models.PositiveIntegerField()),
                ('protein_per_100g', models.FloatField(default=0)),
                ('fat_per_100g', models.FloatField(default=0)),
                ('carbs_per_100g', models.FloatField(default=0)),
                ('is_common', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('workout_type', models.CharField(choices=[('strength', 'Силовая'), ('running', 'Бег'), ('walking', 'Ходьба'), ('swimming', 'Бассейн'), ('stretching', 'Растяжка')], max_length=30)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Мужчина'), ('female', 'Женщина')], max_length=20)),
                ('age', models.PositiveIntegerField()),
                ('height_cm', models.PositiveIntegerField()),
                ('weight_kg', models.FloatField()),
                ('goal', models.CharField(choices=[('fat_loss', 'Похудеть'), ('belly_fat_loss', 'Убрать живот'), ('body_recomposition', 'Похудеть и подкачаться'), ('muscle_gain', 'Набрать мышечную массу'), ('maintain', 'Поддерживать форму')], max_length=40)),
                ('activity_level', models.CharField(choices=[('low', 'Низкая активность'), ('light', 'Легкая активность'), ('medium', 'Средняя активность'), ('high', 'Высокая активность')], default='low', max_length=20)),
                ('has_gym', models.BooleanField(default=False)),
                ('wants_morning_running', models.BooleanField(default=True)),
                ('has_pool', models.BooleanField(default=False)),
                ('meals_per_day', models.PositiveIntegerField(default=4)),
                ('daily_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_protein_g', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FitnessProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='12 недель — убрать живот и войти в форму', max_length=150)),
                ('duration_weeks', models.PositiveIntegerField(default=12)),
                ('start_date', models.DateField()),
                ('daily_calories', models.PositiveIntegerField()),
                ('daily_protein_g', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DayPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('day_number', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('calories_goal', models.PositiveIntegerField()),
                ('protein_goal_g', models.PositiveIntegerField()),
                ('steps_goal', models.PositiveIntegerField(default=7000)),
                ('morning_activity', models.CharField(choices=[('run', 'Бег'), ('walk', 'Ходьба'), ('strength', 'Силовая'), ('swimming', 'Бассейн'), ('rest', 'Отдых'), ('stretching', 'Растяжка')], default='walk', max_length=30)),
                ('evening_activity', models.CharField(choices=[('run', 'Бег'), ('walk', 'Ходьба'), ('strength', 'Силовая'), ('swimming', 'Бассейн'), ('rest', 'Отдых'), ('stretching', 'Растяжка')], default='rest', max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_plans', to='planner.fitnessprogram')),
                ('workout_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.workouttemplate')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DishIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams', models.PositiveIntegerField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='planner.dish')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.food')),
            ],
        ),
        migrations.CreateModel(
            name='MealChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('snack', 'Полдник'), ('dinner', 'Ужин')], max_length=30)),
                ('meal_time', models.TimeField(blank=True, null=True)),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='planner.dayplan')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.dish')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressCheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.FloatField()),
                ('waist_cm', models.FloatField(blank=True, null=True)),
                ('completed_workouts', models.PositiveIntegerField(default=0)),
                ('completed_morning_activities', models.PositiveIntegerField(default=0)),
                ('energy_level', models.PositiveIntegerField(default=5)),
                ('hunger_level', models.PositiveIntegerField(default=5)),
                ('comment', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutTemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.CharField(default='10', max_length=30)),
                ('rest_seconds', models.PositiveIntegerField(default=60)),
                ('order', models.PositiveIntegerField(default=1)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.exercise')),
                ('workout_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='planner.workouttemplate')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserFoodPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('like', 'Ем'), ('dislike', 'Не люблю'), ('avoid', 'Не ем'), ('allergy', 'Аллергия')], max_length=20)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'food')},
            },
        ),
    ]
