# Generated by Django 6.0.6 on 2026-07-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_userdishpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='evening_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='evening_duration_minutes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='morning_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='morning_duration_minutes',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='workouttemplateexercise',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
