# Generated by Django 6.0.6 on 2026-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_dayplan_evening_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='evening_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='morning_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mealchoice',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
