# Generated by Django 6.0.6 on 2026-07-05 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_dayplan_evening_completed_dayplan_morning_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_weight_kg', models.FloatField(blank=True, null=True)),
                ('end_weight_kg', models.FloatField(blank=True, null=True)),
                ('weight_change_kg', models.FloatField(blank=True, null=True)),
                ('start_waist_cm', models.FloatField(blank=True, null=True)),
                ('end_waist_cm', models.FloatField(blank=True, null=True)),
                ('waist_change_cm', models.FloatField(blank=True, null=True)),
                ('avg_energy_level', models.FloatField(blank=True, null=True)),
                ('avg_hunger_level', models.FloatField(blank=True, null=True)),
                ('completed_morning_count', models.PositiveIntegerField(default=0)),
                ('completed_evening_count', models.PositiveIntegerField(default=0)),
                ('total_meals_count', models.PositiveIntegerField(default=0)),
                ('completed_meals_count', models.PositiveIntegerField(default=0)),
                ('completion_percent', models.PositiveIntegerField(default=0)),
                ('calorie_adjustment', models.IntegerField(default=0)),
                ('steps_adjustment', models.IntegerField(default=0)),
                ('recommendation', models.TextField(blank=True)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reviews', to='planner.fitnessprogram')),
            ],
            options={
                'ordering': ['week_number'],
                'unique_together': {('program', 'week_number')},
            },
        ),
    ]
