# Generated by Django 6.0.6 on 2026-07-05 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_weeklyreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraFoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('calories', models.PositiveIntegerField()),
                ('protein_g', models.FloatField(blank=True, default=0)),
                ('fat_g', models.FloatField(blank=True, default=0)),
                ('carbs_g', models.FloatField(blank=True, default=0)),
                ('quantity_description', models.CharField(blank=True, help_text='Например: 1 шоколадка, 2 печенья, 1 стакан сока', max_length=150)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('day_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_foods', to='planner.dayplan')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
