# Generated by Django 6.0.6 on 2026-07-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_extrafoodlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyreview',
            name='avg_extra_calories',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='extra_food_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyreview',
            name='total_extra_calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
