# Generated by Django 6.0.6 on 2026-07-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_weeklyreview_avg_extra_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='cooking_steps',
            field=models.TextField(blank=True),
        ),
    ]
