# Generated by Django 6.0.6 on 2026-07-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_dish_cooking_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayplan',
            name='evening_calories_burned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dayplan',
            name='morning_calories_burned',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
