# Generated by Django 6.0.6 on 2026-07-06 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_dayplan_evening_calories_burned_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'В процессе'), ('finished', 'Завершена')], default='in_progress', max_length=30)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('day_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workout_session', to='planner.dayplan')),
                ('workout_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.workouttemplate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutSessionExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_exercises', to='planner.workoutsession')),
                ('template_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.workouttemplateexercise')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
