# Generated by Django 6.0.6 on 2026-07-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0010_workoutsession_workoutsessionexercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitnessprofile',
            name='timezone',
            field=models.CharField(default='Asia/Almaty', help_text='Часовой пояс пользователя', max_length=64),
        ),
    ]
